fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    webapp_config: git://github.com/hairmare/puppet-webapp-config.git
    firewall: git://github.com/puppetlabs/puppetlabs-firewall.git
    apache: git://github.com/purplehazech/puppetlabs-apache.git
    gentoo: git://github.com/gentoo/puppet-portage.git
  symlinks:
    zabbix : "#{source_dir}"
