rvm:
  - 1.8.7
  - 1.9.3
before_script:
  - sudo apt-get update -y
  - sudo apt-get install update-manager-core
  - sudo do-release-upgrade -d -f DistUpgradeViewNonInteractive
  - wget http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.4-1+trusty_all.deb
  - sudo dpkg -i zabbix-release_2.4-1+trusty_all.deb
  - sudo apt-get update -y
  - sudo apt-get install -y zabbix-server-mysql php5-mysql zabbix-frontend-php libapache2-mod-php5
  - mysql -u root -e "drop database if exists zabbix; create database zabbix"
  - mysql -u root -e "create user 'zabbix'@'%' identified by 'zabbix'"
  - mysql -u root -e "grant all privileges on zabbix.* to 'zabbix'@'%'"
  - find /usr/share/zabbix/ -name '*.sql'
  - cat /usr/share/zabbix-server-mysql/schema.sql | mysql -uroot zabbix
  - cat /usr/share/zabbix-server-mysql/images.sql | mysql -uroot zabbix
  - cat /usr/share/zabbix-server-mysql/data.sql | mysql -uroot zabbix
  - sudo a2enmod php5
  - sudo service apache2 restart
  - sudo service zabbix-server start
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec"
env:
  - PUPPET_VERSION=3.7.3
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.0.2
matrix:
  allow_failures:
    - rvm: 1.9.3
