rvm:
  - 1.8.7
  - 1.9.3
before_script:
  - echo "deb http://ppa.launchpad.net/tbfr/zabbix/ubuntu precise main" > zabbix.list
  - echo "deb-src http://ppa.launchpad.net/tbfr/zabbix/ubuntu precise main" >> zabbix.list
  - sudo mv zabbix.list /etc/apt/sources.list.d/
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C407E17D5F76A32B
  - sudo apt-get update -y
  - sudo apt-get install -y zabbix-server-mysql php5-mysql zabbix-frontend-php libapache2-mod-php5
  - mysql -u root -e "create database zabbix"
  - mysql -u root -e "create user 'zabbix'@'%' identified by 'zabbix'"
  - mysql -u root -e "grant all privileges on zabbix.* to 'zabbix'@'%'"
  - gunzip -c /usr/share/zabbix-server-mysql/schema.sql.gz | mysql -uzabbix -pzabbix zabbix
  - gunzip -c /usr/share/zabbix-server-mysql/images.sql.gz | mysql -uzabbix -pzabbix zabbix
  - gunzip -c /usr/share/zabbix-server-mysql/data.sql.gz | mysql -uzabbix -pzabbix zabbix
  - sudo cp /usr/share/doc/zabbix-frontend-php/examples/apache.conf /etc/apache2/mods-available/zabbix.conf
  - sudo ln -s ../mods-available/zabbix.conf /etc/apache2/mods-enabled/zabbix.conf
  - sudo a2enmod php5
  - sudo service apache2 restart
  - sudo sed -i -e 's/START=no/START=yes/' /etc/default/zabbix-server
  - curl -fsSL https://gist.githubusercontent.com/hairmare/b8d75af34c213585f543/raw/7d1af7dffeb4badc543d3d0094c980ef1c2625d6/zabbix.confzabbix/conf/zabbix.conf.php
  - sudo service zabbix-server start
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec"
env:
  - PUPPET_VERSION=3.7.3
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.0.2
matrix:
  allow_failures:
    - rvm: 1.9.3
