rvm:
  - 1.8.7
  - 1.9.3
before_script:
  - sudo apt-get update -y
  - sudo apt-get install update-manager-core
  - sudo do-release-upgrade -d -f DistUpgradeViewNonInteractive
  - wget http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.4-1+trusty_all.deb
  - sudo dpkg -i zabbix-release_2.4-1+trusty_all.deb
  - sudo apt-get update -y
  - sudo apt-get install -y zabbix-server-mysql php5-mysql zabbix-frontend-php libapache2-mod-php5
  - mysql -u root -e "drop database if exists zabbix; create database zabbix"
  - mysql -u root -e "create user 'zabbix'@'%' identified by 'zabbix'"
  - mysql -u root -e "grant all privileges on zabbix.* to 'zabbix'@'%'"
  - ls /usr/share/zabbix/
  - cat /usr/share/zabbix-server-mysql/schema.sql | mysql -uzabbix -pzabbix zabbix
  - cat /usr/share/zabbix-server-mysql/images.sql | mysql -uzabbix -pzabbix zabbix
  - cat /usr/share/zabbix-server-mysql/data.sql | mysql -uzabbix -pzabbix zabbix
  - sudo cp /usr/share/doc/zabbix-frontend-php/examples/apache.conf /etc/apache2/mods-available/zabbix.conf
  - sudo ln -s ../mods-available/zabbix.conf /etc/apache2/mods-enabled/zabbix.conf
  - sudo a2enmod php5
  - sudo service apache2 restart
  - sudo bash -c 'echo "DBPassword=zabbix" >> /etc/zabbix/zabbix_server.conf'
  - sudo sed -i -e 's/START=no/START=yes/' /etc/default/zabbix-server
  - sudo bash -c 'curl -fsSL https://gist.githubusercontent.com/hairmare/b8d75af34c213585f543/raw/7d1af7dffeb4badc543d3d0094c980ef1c2625d6/zabbix.conf > /etc/zabbix/zabbix.conf.php'
  - sudo service zabbix-server start
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec"
env:
  - PUPPET_VERSION=3.7.3
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.0.2
matrix:
  allow_failures:
    - rvm: 1.9.3
