rvm:
  - 1.8.7
  - 1.9.3
script:
  - "rake spec"
env:
#  - PUPPET_VERSION=3.0.1 Breaks due to rodjek/rspec-puppet#58
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=2.7.20
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.6
matrix:
  allow_failures:
    - env: PUPPET_VERSION=2.6.9
    - rvm: 1.9.3
