name 'purplehazech-zabbix'
version '0.0.1'

author 'Lucas S. Bickel'
license 'GNU Affero General Public License, version 3'
project_page 'https://github.com/purplehazech/puppet-infra-project'
source 'https://github.com/purplehazech/puppet-infra-project/tree/master/modules/zabbix'
summary 'install and configure zabbix agent'
description 'Simply installs and configure a zabbix agent. I also plan on doing server and frontend later on.'
dependency 'puppetlabs/stdlib', '~3.2.0'
dependency 'hairmare/webapp_config', '>=1.0.0'
dependency 'purplehazech/apache', '>=0.5.0'
